version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
      #- /mnt/wsl:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mysql:8.0.25
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: kodas123
      MYSQL_DATABASE: lara-firms
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1